### ISSUE TITLE
Illustrative Example

### ISSUE THREAD

**Issue by iMac-ant** [damorimRG/nids-rule-learner#1]
Hi guys, 

could I ask you the benign.pcap and rules.rules useful to reproduce the experiment? I'm not able to find them in Datasets. 

Thanks in advance.

Antonio

**Comment by iMac-ant** [comment]
Moreover, I tested your tool with some data and it does not run. In particular, it works with just one argument (attack), which is the attack.pcap in Datasets folder and not require goodware.pcap and rules.rules. By passing just "synflood.pcap" for example, it stops in optimizerule(). Can I have the correct source code, which is able to reprdouce the illustative example? 

Thank you very much.

**Comment by augustoolucas** [comment]
benign.pcap is an example name of any pcap file containing packages considered as normal traffic, i.e. not malign. You can use the [sample captures from tcpreplay](https://tcpreplay.appneta.com/wiki/captures.html). 

rules.rules is a file containing curated/real rules. We've used the [ones from Suricata](https://rules.emergingthreats.net/open/suricata/rules/).

About the execution error, the code expects arguments for all three input parameters.

**Comment by iMac-ant** [comment]
Thanks for the feedback, but when I give the three parameters, it returns an error because it want just the first parameter and this can be seen in the syrius.py file, between row 23 and row 25.

parser.add_argument('attack', metavar='A') <--- This is the unique input parameter.

**Comment by iMac-ant** [comment]
Hi guys, 

could I have some news about this issue? I would like to cite your work in my scientific article and, more specifically, I would like to have a comparison about the rule synthesis capability. 

Thanks in advance.

**Comment by damorim** [comment]
Lucas, would it be possible for you to prepare specific instructions to
reproduce our experiments? Include commands to download the datasets, if
that is not saved in our repository already.

Thanks,
Marcelo

**Comment by iMac-ant** [comment]
Thanks a lot @damorim! 

I'm waiting for yours.

Antonio

**Comment by augustoolucas** [comment]
I'll have a look at it in a few days. Right now I have no access to a machine to run it.

In the meanwhile, @iMac-ant could you please try to run it putting the benign pcap [file named as "positive-http.pcap" in a folder named "Datasets"](https://github.com/STAR-RG/syrius/blob/master/syrius/syrius.py#L1117) and also the rules file named as all_rules.txt inside the same folder?

**Comment by iMac-ant** [comment]
Hi @augustoolucas, I downloaded all the files in your repository, hence the file you cited are already inside the repo. However I have the same errors mentioned above.

**Comment by iMac-ant** [comment]
Hi @augustoolucas, do you have some news?

**Comment by iMac-ant** [comment]
Dear all, 

I'm sorry if I write you again, but for me is necessary to know if it is possible to have the comparison, hence if I could run your tool, in order to move on in my research. 

Could I consider this issue closed? Are there any improvments? 

Thank you in advance. Best regards,

Antonio

**Comment by augustoolucas** [comment]
Hi @iMac-ant, sorry for the late response. I started to look into it, I got to find some files after digging on the devices I used at the time, but anyway... No real improvements yet. Right now, I don't have any estimation of when I could have this fix done, as I'm working on it in my spare time. Excuses apart, I can give you another update after this weekend.

**Comment by iMac-ant** [comment]
Dear @augustoolucas thank you for your feedback. I'll wait this weekend, but please give me some news on the next Monday, to give us the way to follow the best strategy to move on.  

Have a nice we,

Antonio

**Comment by augustoolucas** [comment]
I've pushed a code that works. The README is still outdated, so you must use the command `python syrius <attack>` to run it, the available options for the "attack" parameter are the ones [on the line 18](https://github.com/STAR-RG/syrius/blob/master/syrius/syrius.py#L18).

Off-topic:
I had some trouble when installing Suricata with the installSuricata.sh script, there are lots of missing dependencies. We should probably be using a [Suricata docker image](https://hub.docker.com/layers/jasonish/suricata/4.1.7/images/sha256-17838f3110c8db81f6fc79272383c52f1ef7769828524e02b8234da463cd1a90?context=explore) instead.

**Comment by iMac-ant** [comment]
Hi @augustoolucas, thank you for your feedback! I'm going to run your tool tomorrow and I'll update you about the correct execution of the comparison test with our work.

**Comment by iMac-ant** [comment]
Good morning @augustoolucas, I still got some problems in the execution of your code. Hence, if possible, I ask you to produce the list of rules for synflood anomaly and point to me out the **EXACT** PCAP(s) (both attack and be) used by your tool to obtain the previous cited output. 

Thanks in advance,

Antonio

**Comment by iMac-ant** [comment]
Hi @augustoolucas, could you confirm that if I run your tool, considering the "synflood" anomaly, I'll obtained the following rule? 

**alert tcp any any -> any any (msg: "Testing rule 0"; flags:S; threshold: type both, track by_dst, count 5000, seconds 5; sid:525;)**

Moreover, was **http-positive.pcap** begign traffic used by your tool ? (Or in general the PCAP in sendGoodTraffic.sh)

Thanks in advance, 

Antonio

**Comment by damorim** [comment]
Folks, can you try to run this on Docker to mitigate this reproducibility
concern?

Marcelo

**Comment by iMac-ant** [comment]
Dear @damorim, I run locally your tool with Suricata correctly installed. I passed "synflood" on python3 syrius.py as argument and the code works, considering the synflood.pcap file in Datasets folder of your repository. The rules obtained is the above mentioned. By checking the source code of Syrius, the rule options of generated rule are correct. I used your files. Why should I use Docker? 

Thank you in advance.

Antonio

**Comment by damorim** [comment]
Hi Antonio, my understanding was that you and Lucas were observing
different outputs. In that case, Docker would enable you to observe the
same output as that would enforce you to use the same environment. Ignore
my message if that was not the case.

Marcelo

**Comment by iMac-ant** [comment]
Dear Marcelo, your idea is clear, but as you said, this was not the case.  I just answered the correctness of the rule obtained in order to compare it with my rule generated by our tool considering the same input data, which are taken from your repo. Hence, the reproducibility of the experiments should be guaranted by the usage of the same code and same data.

Antonio

**Comment by augustoolucas** [comment]
I'll try to take a look into it today. Sorry for the late reply.

**Comment by augustoolucas** [comment]
> Hi @augustoolucas, could you confirm that if I run your tool, considering the "synflood" anomaly, I'll obtained the following rule?
> 
> **alert tcp any any -> any any (msg: "Testing rule 0"; flags:S; threshold: type both, track by_dst, count 5000, seconds 5; sid:525;)**
> 
> Moreover, was **http-positive.pcap** begign traffic used by your tool ? (Or in general the PCAP in sendGoodTraffic.sh)
> 
> Thanks in advance,
> 
> Antonio

Yes and yes. It outputs a single rule, although the rule I got here has a wrongly formatted msg field, I'm not sure why, but that's not relevant. The other options are the same as yours.

**Comment by iMac-ant** [comment]
Dear all, thanks for your overall contribute. I close this issue. Have a nice day and good luck for your future works!

Antonio
